WorldWideTelescope/wwt_data_formats

CHANGES.md
README.md
docs/conf.py
docs/index.rst
docs/installation.rst
setup.py

Get it out there so we can on ReadTheDocs!

Release PR for version 0.0.1

---

wwt_data_formats/imageset.py
wwt_data_formats/tests/test_imageset.py

Enough to get imagesets with WCS that seems to work ...

Basic support for tiled studies

---

CHANGES.md
wwt_data_formats/__init__.py
wwt_data_formats/enums.py
wwt_data_formats/imageset.py
wwt_data_formats/tests/test_imageset.py
wwt_data_formats/tests/test_place.py

Based on some initial experiences with serializing and deserializing actual files from the wild.

XML serialization fixes

---

wwt_data_formats/__init__.py
wwt_data_formats/folder.py
wwt_data_formats/imageset.py
wwt_data_formats/place.py
wwt_data_formats/tests/test_folder.py
wwt_data_formats/tests/test_imageset.py
wwt_data_formats/tests/test_place.py

Working on some tools for exploring the data collections ...

Walking Folder trees

---

.travis.yml
setup.py
wwt_data_formats/__init__.py
wwt_data_formats/cli.py
wwt_data_formats/enums.py
wwt_data_formats/filecabinet.py
wwt_data_formats/folder.py
wwt_data_formats/place.py
wwt_data_formats/tests/test_filecabinet.py
wwt_data_formats/tests/test_folder.py

I thought that maybe we wouldn't need it, but there are a few things usefully exposed through a CLI.

Add CLI tool

---

CHANGES.md
MANIFEST.in
docs/conf.py
setup.py

Main feature is to add first-cut WWTL support.

Release PR for version 0.2.0

---

docs/api.rst
docs/api/wwt_data_formats.abcs.UrlContainer.rst
docs/api/wwt_data_formats.cli.serve_getparser.rst
docs/api/wwt_data_formats.cli.serve_impl.rst
docs/api/wwt_data_formats.cli.wtml_getparser.rst
docs/api/wwt_data_formats.cli.wtml_impl.rst
docs/api/wwt_data_formats.cli.wtml_rewrite_urls.rst
docs/api/wwt_data_formats.folder.make_absolutizing_url_mutator.rst
docs/api/wwt_data_formats.server.run_server.rst
wwt_data_formats/__init__.py
wwt_data_formats/abcs.py
wwt_data_formats/cli.py
wwt_data_formats/folder.py
wwt_data_formats/imageset.py
wwt_data_formats/layers.py
wwt_data_formats/place.py
wwt_data_formats/server.py
wwt_data_formats/tests/test1_rel.wtml
wwt_data_formats/tests/test_folder.py
wwt_data_formats/tests/test_server.py

Based on a month of data processing with David Weigel.

Some ergonomics

---

CHANGES.md
docs/api.rst
docs/cli.rst
docs/cli/cabinet-list.rst
docs/cli/cabinet-pack.rst
docs/cli/cabinet-unpack.rst
docs/cli/serve.rst
docs/cli/wtml-rewrite-urls.rst
docs/conf.py
docs/index.rst
setup.py

We'll also call this the 0.4.0 release.

docs: start CLI tool documentation

---

CHANGES.md
docs/conf.py
setup.py

Get the Windows test suite fixed in case that will help with getting this package onto conda-forge.

Release 0.4.1

---

.coveralls.yml
docs/imagesets.rst
setup.py
wwt_data_formats/__init__.py
wwt_data_formats/cli.py
wwt_data_formats/folder.py
wwt_data_formats/tests/test_filecabinet.py
wwt_data_formats/tests/test_folder.py

- Remove Coveralls vestiges
- Try to be thorough about using UTF-8 for text everywhere.

Small updates

---

ci/azure-build-and-test.yml

And fixing the docs should be pretty easy I think.

ci: duh, can't release without fixing docs

---

README.md
ci/azure-build-and-test.yml
docs/api/wwt_data_formats.cli.wtml_report.rst
docs/cli.rst
docs/cli/wtml-report.rst
setup.py
wwt_data_formats/__init__.py
wwt_data_formats/cli.py
wwt_data_formats/tests/report_rel.wtml
wwt_data_formats/tests/test_folder.py

A simple validator for Toasty pipeline WTML files. Our Place Annotation metadata expectations need to be documented at some point.

Add `wwtdatatool wtml report`

---

docs/api/wwt_data_formats.cli.preview_getparser.rst
docs/api/wwt_data_formats.cli.preview_impl.rst
docs/api/wwt_data_formats.server.preview_wtml.rst
docs/cli.rst
docs/cli/preview.rst
docs/cli/serve.rst
wwt_data_formats/cli.py
wwt_data_formats/server.py
wwt_data_formats/tests/test_server.py

As suggested by @astrofrog. Just run
```
wwtdatatool preview myimage/index_rel.wtml
```
and we'll start up a server and pop it open in the webclient!

Add a `wwtdatatool preview` command

---

docs/api/wwt_data_formats.cli.cabinet_getparser.rst
docs/api/wwt_data_formats.cli.cabinet_impl.rst
docs/api/wwt_data_formats.cli.cabinet_list.rst
docs/api/wwt_data_formats.cli.cabinet_pack.rst
docs/api/wwt_data_formats.cli.cabinet_unpack.rst
docs/api/wwt_data_formats.cli.die.rst
docs/api/wwt_data_formats.cli.preview_getparser.rst
docs/api/wwt_data_formats.cli.preview_impl.rst
docs/api/wwt_data_formats.cli.serve_impl.rst
docs/api/wwt_data_formats.cli.tree_fetch.rst
docs/api/wwt_data_formats.cli.tree_getparser.rst
docs/api/wwt_data_formats.cli.tree_impl.rst
docs/api/wwt_data_formats.cli.tree_print_dem_urls.rst
docs/api/wwt_data_formats.cli.tree_print_image_urls.rst
docs/api/wwt_data_formats.cli.tree_summarize.rst
docs/api/wwt_data_formats.cli.warn.rst
docs/api/wwt_data_formats.cli.wtml_getparser.rst
docs/api/wwt_data_formats.cli.wtml_impl.rst
docs/api/wwt_data_formats.cli.wtml_merge.rst
docs/api/wwt_data_formats.cli.wtml_report.rst
docs/api/wwt_data_formats.cli.wtml_rewrite_disk.rst
docs/api/wwt_data_formats.cli.wtml_rewrite_urls.rst
docs/api/wwt_data_formats.cli.wtml_transfer_astrometry.rst
docs/cli.rst
docs/cli/wtml-transfer-astrometry.rst
wwt_data_formats/cli.py
wwt_data_formats/tests/__init__.py
wwt_data_formats/tests/test_wtml_merge.py
wwt_data_formats/tests/test_wtml_transfer.py
wwt_data_formats/tests/test_wtml_tree.py

A command to help smooth the workflow with manual astrometric refinement.

Add `wwtdatatool wtml transfer-astrometry`

---

wwt_data_formats/imageset.py
wwt_data_formats/tests/test_imageset.py

We were ignoring this before and it was leading to confusion. This PR breaks our behavior, but ought to be a much firmer foundation to build upon.

Do a better job handling image parity

---

wwt_data_formats/imageset.py

Based on recent dev work in the engine.

wwt_data_formats/imageset.py: document FileType in more detail

---

docs/api/wwt_data_formats.folder.Folder.rst
docs/cli/preview.rst
wwt_data_formats/cli.py
wwt_data_formats/folder.py
wwt_data_formats/server.py
wwt_data_formats/tests/test_server.py

There are a few pieces to get this working but the upshot is that the `preview` subcommand has a new `-r` option.

Add research app mode to `wwtdatatool preview`

---

docs/api/wwt_data_formats.server.launch_app_for_wtml.rst
docs/cli/serve.rst
wwt_data_formats/cli.py
wwt_data_formats/server.py
wwt_data_formats/tests/test1_rel.wtml
wwt_data_formats/tests/test_server.py

The main thing is that in order to make "toasty view" work over SSH, we need a way to get the server to exit reliably. It's also helpful to make the app-launching functionality more reusable.

Add some features needed for "toasty view" over SSH

---

ci/azure-deployment.yml
ci/azure-sdist.yml
ci/zenodo.json5
docs/cli.rst
docs/cli/show-concept-doi.rst
docs/cli/show-version-doi.rst
docs/cli/show-version.rst
pyproject.toml
wwt_data_formats/cli.py
wwt_data_formats/tests/test_misc.py

Copied nearly verbatim from WorldWideTelescope/toasty#85.
CC @Carifio24 and @imbasimba : FYI.

Add support for DOI registration and display.

---

ci/azure-build-and-test.yml
docs/api/wwt_data_formats.plate.V1PlateReader.rst
docs/api/wwt_data_formats.plate.V1PlateWriter.rst
docs/api/wwt_data_formats.plate.rst
docs/index.rst
wwt_data_formats/plate.py
wwt_data_formats/tests/test_folder.py
wwt_data_formats/tests/test_plate.py

This was surprisingly easy! There's also a V2 format that's a bit more complicated, but we don't do anything about it here (besides document a tiny bit).

Add support for V1 plate files
